# ./.tmuxinator.yml

name: cli-demos
root: .

tmux_command: byobu

windows:
    - ranger:
        - cd ~
        - clear
        - echo -e "\nranger\nDemo in kitty" | boxes -d peek -a c
    - bat:
        - clear
        - echo -e "\nbat slides.md\n" | boxes -d peek -a c
    - (porn) colorls:
        - clear
        - echo -e "\nlc\n" | boxes -d peek -a c
    - (porn) lolcat:
        - clear
        - echo -e "\nla | lolcat\n" | boxes -d peek -a c
    - (porn) no-more-secrets:
        - clear
        - echo -e "\nla | nms | lolcat\n" | boxes -d peek -a c

